// Build: turn posts/*.md into public/posts.js, and assemble the deploy folder.
//
//   node build.mjs
//
// You write markdown in posts/. This produces the posts.js your site loads,
// then copies the static files into public/ for deployment. Never edit
// posts.js by hand — it is generated.

import fs from 'node:fs';
import path from 'node:path';
import { marked } from 'marked';

const ROOT = process.cwd();
const POSTS_DIR = path.join(ROOT, 'posts');
const OUT_DIR = path.join(ROOT, 'public');

const MONTHS = ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];

// ── minimal front-matter parser (--- ... --- at top of file) ──────────────
function parseFrontMatter(raw) {
  if (!raw.startsWith('---')) return { data: {}, body: raw };
  const end = raw.indexOf('\n---', 3);
  if (end === -1) return { data: {}, body: raw };
  const fmBlock = raw.slice(3, end).trim();
  const body = raw.slice(end + 4).replace(/^\s*\n/, '');
  const data = {};
  for (const line of fmBlock.split('\n')) {
    const i = line.indexOf(':');
    if (i === -1) continue;
    const key = line.slice(0, i).trim();
    let val = line.slice(i + 1).trim();
    if (val.startsWith('[') && val.endsWith(']')) {
      val = val.slice(1, -1).split(',').map((s) => s.trim().replace(/^["']|["']$/g, '')).filter(Boolean);
    } else {
      val = val.replace(/^["']|["']$/g, '');
    }
    data[key] = val;
  }
  return { data, body };
}

function formatDate(iso) {
  // "2026-07-06" -> "06 Jul 2026"
  const [y, m, d] = String(iso).split('-');
  return `${d} ${MONTHS[parseInt(m, 10) - 1]} ${y}`;
}

function readingStats(body) {
  // Count prose words, ignoring fenced code blocks and markdown punctuation.
  const prose = body.replace(/```[\s\S]*?```/g, ' ').replace(/[#>*_`\-\[\]()]/g, ' ');
  const words = prose.split(/\s+/).filter(Boolean).length;
  const mins = Math.max(1, Math.round(words / 200));
  return { words: `${words} words`, mins: `${mins} min read` };
}

// ── read + render posts ───────────────────────────────────────────────────
if (!fs.existsSync(POSTS_DIR)) { console.error('No posts/ directory found.'); process.exit(1); }

const files = fs.readdirSync(POSTS_DIR).filter((f) => f.endsWith('.md'));
const posts = files.map((file) => {
  const raw = fs.readFileSync(path.join(POSTS_DIR, file), 'utf8');
  const { data, body } = parseFrontMatter(raw);
  if (!data.title || !data.date) {
    console.error(`! ${file}: missing title or date in front matter — skipped`);
    return null;
  }
  const { words, mins } = readingStats(body);
  return {
    title: data.title,
    date: formatDate(data.date),
    _sort: data.date,
    type: data.type || 'post',
    tags: Array.isArray(data.tags) ? data.tags : (data.tags ? [data.tags] : []),
    words,
    mins,
    content: marked.parse(body).trim(),
  };
}).filter(Boolean);

// newest first
posts.sort((a, b) => (a._sort < b._sort ? 1 : a._sort > b._sort ? -1 : 0));
posts.forEach((p) => delete p._sort);

// ── write public/ ─────────────────────────────────────────────────────────
fs.rmSync(OUT_DIR, { recursive: true, force: true });
fs.mkdirSync(OUT_DIR, { recursive: true });

const banner = '/* AUTO-GENERATED by build.mjs from posts/*.md — do not edit by hand. */\n';
fs.writeFileSync(path.join(OUT_DIR, 'posts.js'), banner + 'const POSTS = ' + JSON.stringify(posts, null, 2) + ';\n');

// Copy static files into public/. Add more names/dirs here if your site grows.
const STATIC_FILES = ['index.html', 'pfp.png', 'favicon.ico', 'robots.txt', 'CNAME', '.nojekyll'];
for (const f of STATIC_FILES) {
  const src = path.join(ROOT, f);
  if (fs.existsSync(src)) fs.copyFileSync(src, path.join(OUT_DIR, f));
}
// Copy an optional static/ directory wholesale (Hugo-style).
const staticDir = path.join(ROOT, 'static');
if (fs.existsSync(staticDir)) fs.cpSync(staticDir, OUT_DIR, { recursive: true });

console.log(`Built ${posts.length} posts -> public/posts.js`);
posts.forEach((p) => console.log(`  · ${p.date}  ${p.title}  (${p.words}, ${p.mins})`));
